# Generated by Django 5.2.7 on 2025-11-04 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroGrupo',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('aprendiz', 'Aprendiz')], max_length=10)),
                ('id_grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, to='grupos.grupo')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Miembro de Grupo',
                'verbose_name_plural': 'Miembros de Grupo',
                'db_table': 'miembros_grupo',
            },
        ),
    ]
