# Generated by Django 5.2.7 on 2025-11-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('id_admin', models.IntegerField()),
                ('nombre_grupo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo_reaccion', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('privado', 'Privado')], max_length=10)),
                ('fecha_creacion', models.DateField()),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'grupos',
            },
        ),
    ]
