# Generated by Django 5.2.7 on 2025-11-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('numero_ficha', models.IntegerField(primary_key=True, serialize=False)),
                ('programa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
            },
        ),
    ]
