# Generated by Django 5.2.7 on 2025-11-04 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentarios', models.CharField(max_length=1000)),
                ('fecha_comentario', models.DateField()),
                ('id_publicacion', models.ForeignKey(db_column='id_publicacion', on_delete=django.db.models.deletion.CASCADE, to='publicaciones.publicacion')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'comentarios',
            },
        ),
    ]
