# Generated by Django 5.2.7 on 2025-11-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('numero_documento', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('administrador', 'Administrador'), ('aprendiz', 'Aprendiz'), ('instructor', 'Instructor')], max_length=20)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/%Y/%m/%d/')),
                ('fecha_registro', models.DateField()),
                ('tipo_documento', models.CharField(choices=[('cedula de ciudadania', 'Cédula de Ciudadanía'), ('tarjeta de identidad', 'Tarjeta de Identidad'), ('cedula de extranjeria', 'Cédula de Extranjería'), ('PEP', 'PEP'), ('permiso por proteccion temporal', 'Permiso por Protección Temporal')], max_length=50)),
                ('numero_ficha', models.CharField(max_length=50)),
            ],
        ),
    ]
