# Generated by Django 5.2.8 on 2025-11-12 00:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20)),
                ('rol', models.CharField(choices=[('Aprendiz', 'Aprendiz'), ('Instructor', 'Instructor'), ('Bienestar', 'Bienestar')], max_length=50)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('exito', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'db_table': 'sesion',
            },
        ),
    ]
