# info/settings.py
"""
Django settings for info project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import pymysql
pymysql.install_as_MySQLdb()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent  # QUÉDATE CON ESTA

# Static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # Ahora funciona porque BASE_DIR es Path


SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-clave-por-defecto')

DEBUG = os.getenv('DEBUG', 'True') == 'True'


ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'applications.registro.apps.IndexConfig',
    'applications.sesion',
    'applications.index',
    'applications.usuarios',
    'applications.moderacion',
    'applications.publicaciones',
    'applications.amistades',
    'applications.chat',
    'applications.perfil',
    'applications.notificaciones',
    'applications.busqueda',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'info.urls'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'info.wsgi.application'
ASGI_APPLICATION = 'info.asgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'infosena_db'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'root'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(os.getenv('REDIS_HOST', '127.0.0.1'), int(os.getenv('REDIS_PORT', 6379)))],
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ------------------------------------------
# CONFIGURACIÓN DE CORREO (RECUPERAR CONTRASEÑA)
# ------------------------------------------

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

ADMIN_EMAIL = EMAIL_HOST_USER

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
PERSPECTIVE_API_KEY = os.getenv('PERSPECTIVE_API_KEY', '')
PERSPECTIVE_DEBUG = True
# Modelo de moderación
OPENAI_MODERATION_MODEL = 'omni-moderation-latest'

PERSPECTIVE_THRESHOLDS = {
    'TOXICITY': 0.5,          # Toxicidad general (recomendado: 0.6-0.8)
    'SEVERE_TOXICITY': 0.4,   # Toxicidad severa (recomendado: 0.5-0.7)
    'INSULT': 0.5,            # Insultos directos (recomendado: 0.6-0.8)
    'PROFANITY': 0.5,         # Groserías/palabrotas (recomendado: 0.6-0.8)
    'THREAT': 0.4,            # Amenazas (recomendado: 0.5-0.7)
    'IDENTITY_ATTACK': 0.5,   # Ataques por identidad (recomendado: 0.6-0.8)
}

# Configuración de moderación
MODERACION_CACHE_TIMEOUT = 300
MODERACION_RATE_LIMIT_DELAY = 2  # 2 segundos entre peticiones (NUEVO)
MODERACION_MAX_RETRIES = 3  # Reintentos en caso de error (NUEVO)
MODERACION_RETRY_DELAY = 5  # Espera 5 segundos antes de reintentar (NUEVO)

# 4. Comportamiento cuando falla la API
MODERACION_FALLBACK_MODE = 'permisivo'
MODERACION_MAX_TEXTO_LENGTH = 5000
MODERACION_MAX_IMAGE_SIZE = 10 * 1024 * 1024  # 10MB
MODERACION_MAX_VIDEO_SIZE = 50 * 1024 * 1024  # 50MB

# Categorías bloqueadas
MODERACION_CATEGORIAS_BLOQUEADAS = [
    'sexual', 'sexual/minors', 'violence', 'violence/graphic',
    'harassment', 'harassment/threatening', 'hate', 'hate/threatening',
    'self-harm', 'self-harm/intent', 'self-harm/instructions',
    'illicit', 'illicit/violent'
]

# Palabras prohibidas (personaliza según tu región)
MODERACION_PALABRAS_PROHIBIDAS = [
    'puta', 'puto', 'mierda', 'verga', 'pendejo',
    'gonorrea', 'hijueputa', 'malparido', 'marica',
    'maricon', 'cabron', 'imbecil', 'estupido', 'pito',
    'pene', 'tetas', 'cuca', 'vagina', 'culo', 'tetranutra',
    'cacorro', 'sapo', 'zunga', 'valija', 'pirobo', 'pingo',
    'pato', 'pata', 'mamerto', 'lanpara', 'guisa', 'guaricha'
]

# Caché (opcional pero recomendado)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}
  # ← IMPORTANTE
MODERACION_RATE_LIMIT_DELAY = 3  # 2 segundos entre peticiones

# ---- CONFIGURACIÓN DE PRODUCCIÓN ----
if not DEBUG:
    # Seguridad
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    X_FRAME_OPTIONS = 'DENY'