# Generated by Django 5.2.7 on 2025-11-06 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mensaje', serialize=False, to='chat.chat')),
                ('estado', models.CharField(choices=[('leido', 'Leído'), ('entregado', 'Entregado'), ('enviado', 'Enviado')], default='enviado', max_length=10)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
            },
        ),
    ]
