# Generated by Django 5.2.8 on 2025-11-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('numero_documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('centro_formativo', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=100)),
                ('jornada', models.CharField(max_length=50)),
                ('ficha', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aprendiz',
            },
        ),
        migrations.CreateModel(
            name='Bienestar',
            fields=[
                ('numero_documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('centro_formativo', models.CharField(default='Centro desconocido', max_length=150)),
                ('region', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bienestar',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('numero_documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('centro_formativo', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
    ]
